# Generated by Django 6.0.1 on 2026-01-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('destination_name', models.CharField(max_length=100)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('fare', models.FloatField()),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('boarded', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
