# Generated by Django 6.0.1 on 2026-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='on_bus_break',
            field=models.BooleanField(default=False),
        ),
    ]
